[build]
  publish = "apps/mobile/web-build"
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:mobile"
  port = 8081
  publish = "apps/mobile/web-build"
