[build]
  command = "npm install && npm run build:web --prefix apps/mobile"
  publish = "apps/mobile/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
