[build]
  publish = "apps/mobile/web-build"
  command = "echo 'Build completed - static files ready'"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

